# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCodeOfConduct: true
AddContributionDocs: true
AddCopierCI: true
AddGitHubTemplates: true
AddMacToCI: true
AddPrecommit: true
AddWinToCI: true
AnswerStrategy: ask
AuthorEmail: p.altmeyer@tudelft.nl
AuthorName: Patrick Altmeyer
Indentation: 2
JuliaMinVersion: '1.10'
License: MIT
PackageName: EnergySamplers
PackageOwner: JuliaTrustworthyAI
PackageUUID: dad15e66-0daf-5efc-ba20-16202424f64d
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.9.0
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
